config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :orders

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
 
end

app/models/order.rb
class Order < ActiveRecord::Base
	#mount_uploader :image, ImageUploader
	validates :name, presence: :true
	validates :phone_number, presence: :true, length: { is: 10 }
	validates :cake_size, :date, presence: :true
	validates :delivery_or_pickup, presence: :true
	validates :delivery_address, presence: :true
	validates :d_phone_number, presence: :true
	validates :amount, presence: :true
	validates :paid, presence: :true
	validates :balance, presence: :true
	validates :date, presence: :true, length: { is: 10 }
	validates :time, presence: :true, length: { is: 5 }
	validates :image, presence: :true
	
	mount_uploader :image, PictureUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController



  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
  end
  
  def edit
  end

  def create
    @order = Order.new(order_params)
         if @order.save
          flash[:notice] = "Awsome! Your order is in Kitchen"
            redirect_to  @order
     else 
      render 'new'
     end

    end
def show 
@order = Order.find(params[:id])
end
    def update
    if @order.update(order_params)
      flash[:notice] = "Order was updated successfully."
      redirect_to @order
    else
      render 'edit'
    end
  end
private
  def set_order
    @order = order.find(params[:id])
  end
  

  def order_params  
     params.require(:order).permit(:name, :phone_number, :cake_size, :flavour, :delivery_or_pickup, :delivery_address, :d_phone_number, :amount, :paid, :balance, :date, :time,:image)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def  home
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
      <%= link_to 'Occasionkart', root_path, class: 'navbar-brand'%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
        <ul class='navbar-nav ml-auto'>
                  <li class='nav-item'>
                        <%= link_to("Logout", destroy_user_session_path,
                            class: "btn btn-danger logout-button", method: :delete)%>
                    </li>
                </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bhanu1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="container">
  <% if @order.errors.any? %>
    <h2>The following errors prevented the article from being saved</h2>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="row justify-content-center">
    <div class="col-9">

      
      <%= form_with(model: @order, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>

        <div class="form-group row">
          <%= f.label :Name, class: "col-2 col-form-label text-light" %>
          <div class="col-5">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Name of Customer" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Phone_Number, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :phone_number,  class: "form-control shadow rounded", placeholder: "Phone number of customer" %>
          </div>
        </div>
         
         <div class="form-group row">
          <%= f.label :Cake_Quantity, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :cake_size,  class: "form-control shadow rounded", placeholder: "Cake Quanitity" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Flavour, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :flavour,  class: "form-control shadow rounded", placeholder: "Cake Flavour" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Delivery_or_pickup, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :delivery_or_pickup,  class: "form-control shadow rounded", placeholder: "Delivery or Pickup?" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :delivery_address, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :delivery_address,  class: "form-control shadow rounded", placeholder: "Delivery Adress" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Phone_Number, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :d_phone_number,  class: "form-control shadow rounded", placeholder: "Phone number of receiver" %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :Total_Cost, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :amount,  class: "form-control shadow rounded", placeholder: "Total Cost" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :paid, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :paid,  class: "form-control shadow rounded", placeholder: "Amount Paid" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :balance, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :balance,  class: "form-control shadow rounded", placeholder: "Balance" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :Date, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
           <%= f.label_field :date,   class: "form-control shadow rounded" %>
        </div>
      </div>  
        
        <div class="form-group row">
          <%= f.label :Time_Slag, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.text_field :time,  class: "form-control shadow rounded"%>
          </div>
        </div>
        

        <div class="form-group row">
          <%= f.label :image, class: "col-2 col-form-label text-light" %>
          <div class="col-5"> 
            <%= f.file_field :image, accept: 'image/jpeg,image/jpg,image/png', class: "form-control shadow rounded" %>
          </div>
         
          
        </div>
    
        
          <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
        
        
            <% end %>
    
    <div class="mb-3">
      <%= link_to '[ Cancel and return Back ]', root_path, class: "text-info" %>
    </div>
  </div>
</div>


  
</div>
  
<p><%= link_to 'Cancel and Go back', root_path %></p>

app/views/orders/edit.html.erb
<h1 align="center">order Details</h1>


<table>
<tr>
  <td><strong>Name</strong></td>
  <td><%= @order.name %></td>
</tr>
<tr>
  <td><strong>Phone Number:</strong></td>
  <td><%= @order.phone_number %></td>
</tr>
<tr>
  <td><strong>Cake Size:</strong></td>
  <td><%= @order.cake_size %></td>
</tr>

<tr>
  <td><strong>Flavour:</strong></td>
  <td><%= @order.flavour %></td>
</tr>
<tr>
  <td><strong>Delivery Or Pickup:</strong></td>
  <td><%= @order.delivery_or_pickup %></td>
</tr>
<tr>
  <td><strong>If Delivery, Address:</strong></td>
  <td><%= @order.delivery_address %></td>
</tr>
<tr>
  <td><strong>Delviery Phone Number:</strong></td>
  <td><%= @order.d_phone_number %></td>
</tr>
<tr>
  <td><strong>Amount:</strong></td>
  <td><%= @order.amount %></td>
</tr>
<tr>
  <td><strong>paid:</strong></td>
  <td><%= @order.paid %></td>
</tr>
<tr>
  <td><strong>balance:</strong></td>
  <td><%= @order.balance %></td>
</tr>
<tr>
  <td><strong>Date:</strong></td>
  <td><%= @order.date %></td>
</tr>
<tr>
  <td><strong>Time:</strong></td>
  <td><%= @order.time %></td>
</tr>
<tr>
  <td><strong>Image</strong></td>
  <td><%= image_tag(@order.image_url.to_s) %></td>
</tr>
</table>
</div>


<h4 align="center"><%= link_to 'View all orders', orders_path %> | <%= link_to 'Make New order' , new_order_path %></h4>

app/views/orders/index.html.erb
<h1>All ORDERS </h1>
 
<table class="table">
  <tr>
    <th>Name</th>
    <th>Phone Number</th>
    <th>Cake Size</th>
    <th>Flavour</th>
     <th>Delivery or Pickup</th>
     <th> If Delivery, Address:</th>
     <th>Delivery Phone number</th>
     <th>Amount</th>
     <th>Paid</th>
     <th>Balance or COD</th>
    <th>Date</th>
    <th>Time</th>
    <th>Image</th>
    

  </tr>
 
  <% @orders.each do |order| %>
   
    <tr>
      <td><%= order.name %></td>
      <td><%= order.phone_number %></td>
      <td><%= order.cake_size %></td>
      <td><%= order.flavour %></td>
      <td><%= order.delivery_or_pickup %></td>
      <td><%= order.delivery_address %></td>
      <td><%= order.d_phone_number %></td>
      <td><%= order.amount %></td>
      <td><%= order.paid %></td>
      <td><%= order.balance %></td>
      <td><%= order.date %></td>
      <td><%= order.time %></td>
      <td><%= image_tag order.image.url, size: "100x100" %></td>
      <td><%= link_to 'Details', order_path(order) %> </td>
       <td> <%= link_to "Edit", edit_order_path(order), class: "btn btn-outline-info" %></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Back', root_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<h1 align="center">order Details</h1>


<table>
<tr>
  <td><strong>Name</strong></td>
  <td><%= @order.name %></td>
</tr>
<tr>
  <td><strong>Phone Number:</strong></td>
  <td><%= @order.phone_number %></td>
</tr>
<tr>
  <td><strong>Cake Size:</strong></td>
  <td><%= @order.cake_size %></td>
</tr>

<tr>
  <td><strong>Flavour:</strong></td>
  <td><%= @order.flavour %></td>
</tr>
<tr>
  <td><strong>Delivery Or Pickup:</strong></td>
  <td><%= @order.delivery_or_pickup %></td>
</tr>
<tr>
  <td><strong>If Delivery, Address:</strong></td>
  <td><%= @order.delivery_address %></td>
</tr>
<tr>
  <td><strong>Delviery Phone Number:</strong></td>
  <td><%= @order.d_phone_number %></td>
</tr>
<tr>
  <td><strong>Amount:</strong></td>
  <td><%= @order.amount %></td>
</tr>
<tr>
  <td><strong>paid:</strong></td>
  <td><%= @order.paid %></td>
</tr>
<tr>
  <td><strong>balance:</strong></td>
  <td><%= @order.balance %></td>
</tr>
<tr>
  <td><strong>Date:</strong></td>
  <td><%= @order.date %></td>
</tr>
<tr>
  <td><strong>Time:</strong></td>
  <td><%= @order.time %></td>
</tr>
<tr>
  <td><strong>Image</strong></td>
  <td><%= image_tag(@order.image_url.to_s) %></td>
</tr>
</table>
</div>


<h4 align="center"><%= link_to 'View all orders', orders_path %> | <%= link_to 'Make New order' , new_order_path %></h4>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
      <h1 class="display-4">Occasionakart Orders</h1>
      
      <hr class="my-4">
      
      <p align="center"> <%=  link_to "View All Orders", "/orders/", class: "btn btn-danger btn-lg btn-xlarge"  %> </p>
      
   <p align="center"> <%=  link_to "Make A Order", "/orders/new/", class: "btn btn-danger btn-lg btn-xlarge"  %> </p>
</div>
      
    </div>
  </div>
</div>


<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Occasionkart Cakes</small>
    
  </div>
</footer>